name: PageSpeed Insights

on:
  push:
    branches:
    - lighthouse

jobs:
  lighthouse:
    name: Lighthouse Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - name: Run Lighthouse
        env:
          HUBSPOT_PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
        run: npm run lighthouse -- --themeConfirm=true

      - name: PKG versions
        run: |
          node -v
          npm -v
